[build]
  publish = "web"   # The folder where your static files are located
  command = ""      # No build command needed as you're doing everything manually

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
