[build]
  publish = "web"  # Specify that the publish directory is the 'web' folder
  command = ""     # No build command for static sites

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/imgs/*"
  to = "/imgs/:splat"
  status = 200
