[build]
  # The directory to publish to Netlify
  publish = "web"  # Make sure this points to the correct directory (e.g., "web")
  command = ""  # Leave empty if you don't need a build process

[[redirects]]
  # Redirects for routing configuration
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Custom headers for the whole site
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  # Custom headers specifically for images
  for = "/imgs/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Custom headers specifically for the homepage
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"
