[build]
  publish = "web"   # Directory containing your HTML, CSS, JS, and other assets
  command = ""      # No build command needed for a static site

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
