[build]
publish = "web"  # Update with the folder where your static files are located
command = ""     # Leave empty if you don't need a build command

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/img/*"
[headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
