[build]
  publish = "web"  # Directory where your static files (HTML, images) are located
  command = ""  # Leave empty since you're not using a build process

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
