[build]
publish = "web"  # Update with your actual deploy folder (e.g., "public" or "web")
command = ""     # Leave empty if no build process is needed

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/img/*"
[headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
