[build]
  command = ""  # No build command needed for static sites
  publish = "web"  # Publish directory is 'web'

# Optionally, you can add headers or other settings, but redirects are no longer included.
