[build]
  publish = "web"   # This tells Netlify to deploy from the 'web' folder
  command = ""      # No build command since you're manually managing the files

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/img/*"   # This will apply headers for files inside the 'img' folder
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache for 1 year

[[headers]]
  for = "/*"   # This will apply headers globally
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"  # Enforces HTTPS for a year
    X-Content-Type-Options = "nosniff"  # Prevents browsers from interpreting files as other types
