[build]
  publish = "web"  # The directory where index.html is located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/imgs/*"
  to = "/imgs/:splat"
  status = 200
