[build]
  publish = "web"  # Use the "web" folder as the root directory
  command = ""  # No build command needed for manual deployment

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
