[build]
  command = ""  # No build command needed for static sites
  publish = "web"  # The directory containing your site files
  functions = "src/functions"  # Optional: If you have serverless functions

# Redirects Configuration
[[redirects]]
  from = "/old-home"
  to = "/new-home"
  status = 301  # Permanent redirect

[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301  # Permanent redirect

[[redirects]]
  from = "/404.html"
  to = "/index.html"  # Redirect 404 page to homepage
  status = 200  # OK status code

# Headers Configuration
[[headers]]
  for = "/*"  # Apply these headers to all paths
  [headers.values]
    X-Content-Type-Options = "nosniff"  # Prevent MIME-sniffing
    X-Frame-Options = "DENY"  # Prevent page embedding in frames
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"  # Force HTTPS for security

[[headers]]
  for = "/imgs/*"  # Apply headers to all images
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache images for a long time

[[headers]]
  for = "/index.html"  # Apply headers to the index.html (or any other specific page)
  [headers.values]
    Cache-Control = "no-store"  # Prevent caching of the homepage to always serve fresh content
