[build]
  command = ""  # No build command since it's a static site
  publish = "web"  # The folder that contains your site files (web folder)
  functions = "src/functions"  # If you have serverless functions, specify here

# Redirect rules (for URL redirections)
[[redirects]]
  from = "/old-home"
  to = "/new-home"
  status = 301  # Permanent redirect

[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301  # Permanent redirect

# Header rules (for setting HTTP headers)
[[headers]]
  for = "/*"  # Apply these headers to all paths
  [headers.values]
    X-Content-Type-Options = "nosniff"  # Prevent MIME-sniffing attacks
    X-Frame-Options = "DENY"  # Prevent the page from being embedded in a frame
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"  # Force HTTPS

[[headers]]
  for = "/imgs/*"  # Apply these headers to images
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache images for a long time

# Example of a custom 404 page redirection
[[redirects]]
  from = "/404.html"
  to = "/index.html"  # Redirect 404 errors to index page (if required)
  status = 200
